import { ProductProvider } from "./context/ProductContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProductProvider>
            {children}
        </ProductProvider>
      </body>
    </html>
  );
}
